import type { NextPage } from "next";
import { useState, useRef } from "react";
import Head from "next/head";

const Home: NextPage = () => {
  const [uri, setUri] = useState<string>("");

  const inputRef = useRef<HTMLInputElement>(null);

  const _onClick = async (url: string) => {
    if (!url) return;
    const response = await fetch("/api/generateQRCode", {
      method: "POST",
      body: JSON.stringify({ url }),
    });
    const data = await response.json();
    setUri(data.result.dataUrl);
  };

  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-5/6 flex flex-col gap-y-2 mt-8">
        <input className="border border-slate-300" ref={inputRef} />
        <button
          className="text-sm bg-blue-900 text-slate-50 p-2 rounded-md"
          onClick={() => {
            _onClick(inputRef.current!.value);
          }}
        >
          QRコード生成
        </button>
        {!!uri && <img src={uri} alt="generated qrcode" />}
      </main>
    </div>
  );
};

export default Home;
